export { default as Home } from './home'
export { default as Registration } from './registration';
export { default as Login } from "./login";
export { default as ForgotPassword } from './forgotPswd';
export { default as OnlineRep } from './onlineRep';
export { default as OnlineSchool } from './school'
export { default as Profile } from './profile';
export { default as Forum } from './forum/forum';
export { default as Online } from './online/Online';
